{
 "title": "Energy meter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "target", "query": "1000" }
  ]
 },
 "panels": [
  {
   "title": "Power Delta ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT strftime('%s', date_time) AS epoch_time, (total_power - LAG(total_power) OVER (ORDER BY date_time))*1000/0.0833 AS delta, tariff\nFROM energy_meter\n",
     "rawQueryText": "SELECT strftime('%s', date_time) AS epoch_time, (total_power - LAG(total_power) OVER (ORDER BY date_time))*1000/0.0833 AS delta, tariff\nFROM energy_meter\n",
     "timeColumns": [ "epoch_time" ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%dT%H:%M:%S', date_time || 'Z') AS epoch_time, MAX(total_power) - MIN(total_power) AS daily_usage FROM energy_meter\nGROUP BY DATE(epoch_time)\nORDER BY epoch_time DESC\nLIMIT 1",
     "rawQueryText": "SELECT strftime('%Y-%m-%dT%H:%M:%S', date_time || 'Z') AS epoch_time, MAX(total_power) - MIN(total_power) AS daily_usage FROM energy_meter\nGROUP BY DATE(epoch_time)\nORDER BY epoch_time DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts",
      "epoch_time"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH delta_values AS (\nSELECT date_time, COALESCE(total_power - LAG(total_power) OVER (ORDER BY date_time), total_power) AS delta, tariff\nFROM energy_meter\n) \nSELECT strftime('%Y-%m-%dT%H:%M:%S', date_time || 'Z') AS ts, \nSUM(CASE WHEN tariff = 'day' THEN delta ELSE 0 END)*1.09 + SUM(CASE WHEN tariff = 'night' THEN delta ELSE 0 END)*1.09\nFROM delta_values\nGROUP BY DATE(ts)\nORDER BY ts DESC\nLIMIT 1\n",
     "rawQueryText": "WITH delta_values AS (\nSELECT date_time, COALESCE(total_power - LAG(total_power) OVER (ORDER BY date_time), total_power) AS delta, tariff\nFROM energy_meter\n) \nSELECT strftime('%Y-%m-%dT%H:%M:%S', date_time || 'Z') AS ts, \nSUM(CASE WHEN tariff = 'day' THEN delta ELSE 0 END)*1.09 + SUM(CASE WHEN tariff = 'night' THEN delta ELSE 0 END)*1.09\nFROM delta_values\nGROUP BY DATE(ts)\nORDER BY ts DESC\nLIMIT 1\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT total_power-5667.54 FROM energy_meter\nORDER BY date_time DESC\nLIMIT 1",
     "rawQueryText": "SELECT total_power-5667.54 FROM energy_meter\nORDER BY date_time DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH delta_values AS (\nSELECT strftime('%Y-%m-%dT%H:%M:%S', date_time || 'Z') AS ts, COALESCE(total_power - LAG(total_power) OVER (ORDER BY date_time), total_power) AS delta, tariff\nFROM energy_meter\n)\nSELECT ts, \nSUM(CASE WHEN tariff = 'day' THEN delta ELSE 0 END)*1.09 + SUM(CASE WHEN tariff = 'night' THEN delta ELSE 0 END)*1.09\nFROM delta_values\nWHERE ts > '2024-10-31T23:59:00Z'\n\n",
     "rawQueryText": "WITH delta_values AS (\nSELECT strftime('%Y-%m-%dT%H:%M:%S', date_time || 'Z') AS ts, COALESCE(total_power - LAG(total_power) OVER (ORDER BY date_time), total_power) AS delta, tariff\nFROM energy_meter\n)\nSELECT ts, \nSUM(CASE WHEN tariff = 'day' THEN delta ELSE 0 END)*1.09 + SUM(CASE WHEN tariff = 'night' THEN delta ELSE 0 END)*1.09\nFROM delta_values\nWHERE ts > '2024-10-31T23:59:00Z'\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Energy target",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "queryText": "SELECT (total_power-5667.54) AS total_usage FROM energy_meter\nORDER BY id DESC\nLIMIT 1",
     "rawQueryText": "SELECT (total_power-5667.54) AS total_usage FROM energy_meter\nORDER BY id DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT strftime('%s', date_time) AS converted_date, total_power-5667.54 AS total_power FROM energy_meter;",
     "rawQueryText": "SELECT strftime('%s', date_time) AS converted_date, total_power-5667.54 AS total_power FROM energy_meter;",
     "timeColumns": [ "converted_date" ]
    }
   ]
  },
  {
   "title": "Daily power consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT * FROM (\nSELECT strftime('%Y-%m-%dT%H:%M:%SZ', date_time) AS converted_date, MAX(total_power) - MIN(total_power) AS daily_usage FROM energy_meter\nGROUP BY DATE(converted_date)\nORDER BY converted_date DESC\nLIMIT 7)\nORDER BY substr(converted_date,1,10) ASC\n;",
     "rawQueryText": "SELECT * FROM (\nSELECT strftime('%Y-%m-%dT%H:%M:%SZ', date_time) AS converted_date, MAX(total_power) - MIN(total_power) AS daily_usage FROM energy_meter\nGROUP BY DATE(converted_date)\nORDER BY converted_date DESC\nLIMIT 7)\nORDER BY substr(converted_date,1,10) ASC\n;",
     "timeColumns": [ "converted_date" ]
    }
   ]
  },
  {
   "title": "Power consumption by day / stacked",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "queryText": "WITH delta_values AS (\nSELECT date_time, COALESCE(total_power - LAG(total_power) OVER (ORDER BY date_time), total_power) AS delta, tariff\nFROM energy_meter\n)\nSELECT * FROM (\nSELECT strftime('%Y-%m-%dT%H:%M:%SZ', date_time) AS ts, \nSUM(CASE WHEN tariff = 'day' THEN delta ELSE 0 END) AS day_usage,\nSUM(CASE WHEN tariff = 'night' THEN delta ELSE 0 END) AS night_usage\nFROM delta_values\nGROUP BY DATE(ts)\nORDER BY ts DESC\nLIMIT 7)\nORDER BY substr(ts,1,10) ASC\n\n",
     "rawQueryText": "WITH delta_values AS (\nSELECT date_time, COALESCE(total_power - LAG(total_power) OVER (ORDER BY date_time), total_power) AS delta, tariff\nFROM energy_meter\n)\nSELECT * FROM (\nSELECT strftime('%Y-%m-%dT%H:%M:%SZ', date_time) AS ts, \nSUM(CASE WHEN tariff = 'day' THEN delta ELSE 0 END) AS day_usage,\nSUM(CASE WHEN tariff = 'night' THEN delta ELSE 0 END) AS night_usage\nFROM delta_values\nGROUP BY DATE(ts)\nORDER BY ts DESC\nLIMIT 7)\nORDER BY substr(ts,1,10) ASC\n\n",
     "timeColumns": [ "ts" ]
    }
   ]
  }
 ]
}